### PR TITLE
Add resource_count 

### LINKED ISSUE #4: handle manifests with multiple resources?

### PR DESCRIPTION
**Pull request by gordalina**
Adds a new optional variable `resource_count` which asserts that the number of resources created are equal to the given value. When this variable is not defined, no check is made.

Fixes #4

### CODE REVIEW

**Comment by ericchiang** [comment]
This check is there to make sure the next line returns something sane

```
selflink := data.Items[0].Metadata.Selflink
```

To support multiple resources, we'd want to track all the returned selflinks and encode them in the ID.

**Comment by gordalina** [comment]
@ericchiang pushed a commit to address your comment

**Comment by ericchiang** [comment]
Thanks! Unfortunately, terraform plugins also need to read the self link data when performing a delete, and to determine if the resource still exists remotely. You can see the code here:

```
	resource, namespace, ok := resourceFromSelflink(d.Id())
```

So more of the plugin needs to change to handle the new ID format. The ID format also needs to be backward compatible. The plugin has to understand old IDs as well for data that's already been persisted.

Give me a sec. I can make the changes.

**Comment by gordalina** [comment]
Awesome, appreciate it!

**Comment by ericchiang** [comment]
Can you take a look at #21 and maybe test it?

**Comment by gordalina** [comment]
Closing in favor of #21 and #23

**Pull request closed without merging**
